# Generated by Django 5.0.4 on 2025-03-25 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFileImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFileVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
