# Generated by Django 5.0.4 on 2025-04-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafilevideo',
            name='hls_playlist',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
