# Generated by Django 5.0.4 on 2025-04-14 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0002_mediafilevideo_hls_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mediafileimage',
            name='file',
            field=models.FileField(upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='mediafilevideo',
            name='file',
            field=models.FileField(upload_to='uploads/videos/'),
        ),
    ]
