# Generated by Django 5.0.4 on 2025-04-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0003_document_alter_mediafileimage_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='self_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mediafileimage',
            name='self_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mediafilevideo',
            name='self_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
